export class GeneralMemory {
    A: number = 0;
    B: number = 0;
    C: number = 0;
    D: number = 0;
    E: number = 0;
    F: number = 0;
    G: number = 0;
    H: number = 0;
    I: number = 0;
    AX: number = 0;
    BX: number = 0;
    CX: number = 0;
    DX: number = 0;
    EX: number = 0;
    FX: number = 0;
    GX: number = 0;
    HX: number = 0;
}